#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of the skonfig set __redmine.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer checks if the desired version is extraced at $install_dir.
#

install_dir='/usr/local/share/redmine'

# shellcheck disable=SC2015
config_yml="${install_dir:?}/config/configuration.yml"
test -d "${install_dir:?}" && test -f "${config_yml}" || {
	# absent
	exit 0
}

# Only print lines starting with at least two spaces between "production:" and
# the next non-indented line removing the leading two spaces.
sed -n -e '/^production:/,/^[^ ]/s/^  //p' "${config_yml}"
