#!/bin/sh -e
#
# 2021-2022 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __redmine.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer checks if all required Gems are installed.
#

install_dir='/usr/local/share/redmine'

BUNDLE_APP_CONFIG=${install_dir:?}/.bundle
export BUNDLE_APP_CONFIG

test -d "${install_dir}" -a -d "${BUNDLE_APP_CONFIG}" || {
	echo 'absent'
	exit 0
}

cd "${install_dir:?}"

command -v bundle >/dev/null 2>&1 || {
	echo 'absent'
	exit 0
}

if bundle check >/dev/null
then
	# NOTE: sync bundle outdated options with gencode-remote (bundle_doas update)
	if test -f "${__object:?}/parameter/update-gems" \
		&& ! bundle outdated --strict >/dev/null
	then
		echo 'outdated'
	else
		echo 'present'
	fi
else
	echo 'absent'
fi
