#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer checks if all required Gems are installed.
#

install_dir='/usr/local/share/redmine'

test -d "${install_dir:?}" || {
	echo 'absent'
	exit 0
}

command -v bundle >/dev/null 2>&1 || {
	echo 'absent'
	exit 0
}

if (cd "${install_dir:?}" && bundle check) >/dev/null
then
	echo 'present'
else
	echo 'absent'
fi
