#!/bin/sh -e
#
# 2021 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __redmine.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer prints the attributes set on the auth source (if defined) in the format:
# key=value
#

install_dir=/usr/local/share/redmine
svc_user=redmine

RAILS_ENV=production
export RAILS_ENV

id "${svc_user}" >/dev/null 2>&1 || {
	# $svc_user does not exist
	exit 0
}

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
rails_cmd() {
	_env=$(POSIXLY_CORRECT=1 export -p | sed -n -e 's/\(^\|.* \)\(\(BUNDLE\|RAILS\|REDMINE\|_\)_[^=]\{1,\}=.*\)$/\2/p' | tr '\n' ' ')
	su -l "${svc_user}" -s /bin/sh -c "cd $(quote "${install_dir}") && ${_env% } bundle exec rails runner $(quote "$*")"
	unset -v _env
}

if test -s "${__object:?}/parameter/name"
then
	read -r __as_name <"${__object:?}/parameter/name"
else
	__as_name=${__object_id:?}
fi
export __as_name

rails_cmd 'AuthSource.find_by(name: ENV["__as_name"])&.attributes&.sort&.each{ |k, v| puts [k, v].join("=") }'
